
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

from tkinter import *


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("699x481")
window.configure(bg = "#051E35")


canvas = Canvas(
    window,
    bg = "#051E35",
    height = 481,
    width = 699,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    154.0,
    29.0,
    546.0,
    75.0,
    fill="#000000",
    outline="")

canvas.create_text(
    177.0,
    41.0,
    anchor="nw",
    text="WELCOME TO THIS PAGE",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    37.0,
    94.0,
    anchor="nw",
    text="Please enter your details",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    61.0,
    141.0,
    anchor="nw",
    text="First name",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    61.0,
    188.0,
    anchor="nw",
    text="Second name",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    61.0,
    235.0,
    anchor="nw",
    text="Email address",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    61.0,
    282.0,
    anchor="nw",
    text="Phone NO",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    61.0,
    329.0,
    anchor="nw",
    text="Password",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png")
)
entry_bg_1 = canvas.create_image(
    341.5,
    146.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    highlightthickness=0
)
entry_1.place(
    x=204.0,
    y=132.0,
    width=275.0,
    height=26.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png")
)
entry_bg_2 = canvas.create_image(
    341.5,
    340.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    highlightthickness=0
)
entry_2.place(
    x=204.0,
    y=326.0,
    width=275.0,
    height=26.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png")
)
entry_bg_3 = canvas.create_image(
    341.5,
    296.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    highlightthickness=0
)
entry_3.place(
    x=204.0,
    y=282.0,
    width=275.0,
    height=26.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png")
)
entry_bg_4 = canvas.create_image(
    341.5,
    245.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#D9D9D9",
    highlightthickness=0
)
entry_4.place(
    x=204.0,
    y=231.0,
    width=275.0,
    height=26.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png")
)
entry_bg_5 = canvas.create_image(
    341.5,
    198.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#D9D9D9",
    highlightthickness=0
)
entry_5.place(
    x=204.0,
    y=184.0,
    width=275.0,
    height=26.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=418.0,
    y=401.0,
    width=161.0,
    height=40.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=113.0,
    y=401.0,
    width=161.0,
    height=40.0
)
window.resizable(False, False)
window.mainloop()